version: '3'
services:
  db: 
    build: 
      dockerfile: Dockerfile.db
    env_file:
      - .env
  www:
    build: 
      dockerfile: Dockerfile.app
    ports:
      - "127.0.0.1:80:80" # Bind to 127.0.0.1 instead of all interfaces

# # Optional for accessing the database visually
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - 8001:80
#     environment:
#       - PMA_HOST=db
#       - PMA_PORT=3306