version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: echo "cloned the repo"
          command: cp .env.example .env
      - run: 
          name: echo "adding password"
          command: echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
                   cat .env
                  

# Orchestrate our job run sequence
workflows:
  testing-config:
    jobs:
      - build
